# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/fdm.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/fdm.proto',
  package='huginn',
  serialized_pb='\n\x12protobuf/fdm.proto\x12\x06huginn\"_\n\x03GPS\x12\x10\n\x08latitude\x18\x01 \x02(\x01\x12\x11\n\tlongitude\x18\x02 \x02(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x02(\x01\x12\x10\n\x08\x61irspeed\x18\x04 \x02(\x01\x12\x0f\n\x07heading\x18\x05 \x02(\x01\"W\n\rAccelerometer\x12\x16\n\x0ex_acceleration\x18\x01 \x02(\x01\x12\x16\n\x0ey_acceleration\x18\x02 \x02(\x01\x12\x16\n\x0ez_acceleration\x18\x03 \x02(\x01\"D\n\tGyroscope\x12\x11\n\troll_rate\x18\x01 \x02(\x01\x12\x12\n\npitch_rate\x18\x02 \x02(\x01\x12\x10\n\x08yaw_rate\x18\x03 \x02(\x01\"\"\n\x0bThermometer\x12\x13\n\x0btemperature\x18\x01 \x02(\x01\"\"\n\x0ePressureSensor\x12\x10\n\x08pressure\x18\x01 \x02(\x01\"\x1d\n\tPitotTube\x12\x10\n\x08pressure\x18\x01 \x02(\x01\"*\n\x06\x45ngine\x12\x0e\n\x06thrust\x18\x01 \x02(\x01\x12\x10\n\x08throttle\x18\x02 \x02(\x01\"O\n\x08\x43ontrols\x12\x0f\n\x07\x61ileron\x18\x01 \x02(\x01\x12\x10\n\x08\x65levator\x18\x02 \x02(\x01\x12\x0e\n\x06rudder\x18\x03 \x02(\x01\x12\x10\n\x08throttle\x18\x04 \x02(\x01\"\"\n\x03INS\x12\x0c\n\x04roll\x18\x01 \x02(\x01\x12\r\n\x05pitch\x18\x02 \x02(\x01\"\xe5\x02\n\x07\x46\x44MData\x12\x0c\n\x04time\x18\x01 \x02(\x01\x12\x18\n\x03gps\x18\x02 \x02(\x0b\x32\x0b.huginn.GPS\x12,\n\raccelerometer\x18\x03 \x02(\x0b\x32\x15.huginn.Accelerometer\x12$\n\tgyroscope\x18\x04 \x02(\x0b\x32\x11.huginn.Gyroscope\x12(\n\x0bthermometer\x18\x05 \x02(\x0b\x32\x13.huginn.Thermometer\x12/\n\x0fpressure_sensor\x18\x06 \x02(\x0b\x32\x16.huginn.PressureSensor\x12%\n\npitot_tube\x18\x07 \x02(\x0b\x32\x11.huginn.PitotTube\x12\x1e\n\x06\x65ngine\x18\x08 \x02(\x0b\x32\x0e.huginn.Engine\x12\"\n\x08\x63ontrols\x18\t \x02(\x0b\x32\x10.huginn.Controls\x12\x18\n\x03ins\x18\n \x02(\x0b\x32\x0b.huginn.INS')




_GPS = _descriptor.Descriptor(
  name='GPS',
  full_name='huginn.GPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='huginn.GPS.latitude', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='huginn.GPS.longitude', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='huginn.GPS.altitude', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='airspeed', full_name='huginn.GPS.airspeed', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heading', full_name='huginn.GPS.heading', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=125,
)


_ACCELEROMETER = _descriptor.Descriptor(
  name='Accelerometer',
  full_name='huginn.Accelerometer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_acceleration', full_name='huginn.Accelerometer.x_acceleration', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_acceleration', full_name='huginn.Accelerometer.y_acceleration', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z_acceleration', full_name='huginn.Accelerometer.z_acceleration', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=127,
  serialized_end=214,
)


_GYROSCOPE = _descriptor.Descriptor(
  name='Gyroscope',
  full_name='huginn.Gyroscope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll_rate', full_name='huginn.Gyroscope.roll_rate', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch_rate', full_name='huginn.Gyroscope.pitch_rate', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw_rate', full_name='huginn.Gyroscope.yaw_rate', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=216,
  serialized_end=284,
)


_THERMOMETER = _descriptor.Descriptor(
  name='Thermometer',
  full_name='huginn.Thermometer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='huginn.Thermometer.temperature', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=286,
  serialized_end=320,
)


_PRESSURESENSOR = _descriptor.Descriptor(
  name='PressureSensor',
  full_name='huginn.PressureSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pressure', full_name='huginn.PressureSensor.pressure', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=322,
  serialized_end=356,
)


_PITOTTUBE = _descriptor.Descriptor(
  name='PitotTube',
  full_name='huginn.PitotTube',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pressure', full_name='huginn.PitotTube.pressure', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=358,
  serialized_end=387,
)


_ENGINE = _descriptor.Descriptor(
  name='Engine',
  full_name='huginn.Engine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thrust', full_name='huginn.Engine.thrust', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='throttle', full_name='huginn.Engine.throttle', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=389,
  serialized_end=431,
)


_CONTROLS = _descriptor.Descriptor(
  name='Controls',
  full_name='huginn.Controls',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aileron', full_name='huginn.Controls.aileron', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elevator', full_name='huginn.Controls.elevator', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rudder', full_name='huginn.Controls.rudder', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='throttle', full_name='huginn.Controls.throttle', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=433,
  serialized_end=512,
)


_INS = _descriptor.Descriptor(
  name='INS',
  full_name='huginn.INS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll', full_name='huginn.INS.roll', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='huginn.INS.pitch', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=514,
  serialized_end=548,
)


_FDMDATA = _descriptor.Descriptor(
  name='FDMData',
  full_name='huginn.FDMData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='huginn.FDMData.time', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps', full_name='huginn.FDMData.gps', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accelerometer', full_name='huginn.FDMData.accelerometer', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyroscope', full_name='huginn.FDMData.gyroscope', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thermometer', full_name='huginn.FDMData.thermometer', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pressure_sensor', full_name='huginn.FDMData.pressure_sensor', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitot_tube', full_name='huginn.FDMData.pitot_tube', index=6,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='engine', full_name='huginn.FDMData.engine', index=7,
      number=8, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='controls', full_name='huginn.FDMData.controls', index=8,
      number=9, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ins', full_name='huginn.FDMData.ins', index=9,
      number=10, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=551,
  serialized_end=908,
)

_FDMDATA.fields_by_name['gps'].message_type = _GPS
_FDMDATA.fields_by_name['accelerometer'].message_type = _ACCELEROMETER
_FDMDATA.fields_by_name['gyroscope'].message_type = _GYROSCOPE
_FDMDATA.fields_by_name['thermometer'].message_type = _THERMOMETER
_FDMDATA.fields_by_name['pressure_sensor'].message_type = _PRESSURESENSOR
_FDMDATA.fields_by_name['pitot_tube'].message_type = _PITOTTUBE
_FDMDATA.fields_by_name['engine'].message_type = _ENGINE
_FDMDATA.fields_by_name['controls'].message_type = _CONTROLS
_FDMDATA.fields_by_name['ins'].message_type = _INS
DESCRIPTOR.message_types_by_name['GPS'] = _GPS
DESCRIPTOR.message_types_by_name['Accelerometer'] = _ACCELEROMETER
DESCRIPTOR.message_types_by_name['Gyroscope'] = _GYROSCOPE
DESCRIPTOR.message_types_by_name['Thermometer'] = _THERMOMETER
DESCRIPTOR.message_types_by_name['PressureSensor'] = _PRESSURESENSOR
DESCRIPTOR.message_types_by_name['PitotTube'] = _PITOTTUBE
DESCRIPTOR.message_types_by_name['Engine'] = _ENGINE
DESCRIPTOR.message_types_by_name['Controls'] = _CONTROLS
DESCRIPTOR.message_types_by_name['INS'] = _INS
DESCRIPTOR.message_types_by_name['FDMData'] = _FDMDATA

class GPS(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GPS

  # @@protoc_insertion_point(class_scope:huginn.GPS)

class Accelerometer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCELEROMETER

  # @@protoc_insertion_point(class_scope:huginn.Accelerometer)

class Gyroscope(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GYROSCOPE

  # @@protoc_insertion_point(class_scope:huginn.Gyroscope)

class Thermometer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _THERMOMETER

  # @@protoc_insertion_point(class_scope:huginn.Thermometer)

class PressureSensor(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PRESSURESENSOR

  # @@protoc_insertion_point(class_scope:huginn.PressureSensor)

class PitotTube(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PITOTTUBE

  # @@protoc_insertion_point(class_scope:huginn.PitotTube)

class Engine(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENGINE

  # @@protoc_insertion_point(class_scope:huginn.Engine)

class Controls(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLS

  # @@protoc_insertion_point(class_scope:huginn.Controls)

class INS(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INS

  # @@protoc_insertion_point(class_scope:huginn.INS)

class FDMData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FDMDATA

  # @@protoc_insertion_point(class_scope:huginn.FDMData)


# @@protoc_insertion_point(module_scope)
